# Generated by Django 6.0 on 2025-12-27 18:19

import ckeditor.fields
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="car",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="car",
            name="miles",
        ),
        migrations.RemoveField(
            model_name="car",
            name="vin_no",
        ),
        migrations.AlterField(
            model_name="car",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="car",
            name="features",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("air_conditioning", "Klimatyzacja"),
                    ("automatic_climate", "Klimatyzacja automatyczna"),
                    ("heated_seats", "Podgrzewane siedzenia"),
                    ("electric_seats", "Elektrycznie regulowane siedzenia"),
                    ("leather_seats", "Skórzana tapicerka"),
                    ("armrest", "Podłokietnik"),
                    ("keyless", "Dostęp bezkluczykowy"),
                    ("push_start", "Start/Stop Engine"),
                    ("bluetooth", "Bluetooth"),
                    ("usb", "USB"),
                    ("aux", "AUX"),
                    ("apple_carplay", "Apple CarPlay"),
                    ("android_auto", "Android Auto"),
                    ("navigation", "Nawigacja GPS"),
                    ("touchscreen", "Ekran dotykowy"),
                    ("premium_audio", "Nagłośnienie premium"),
                    ("abs", "ABS"),
                    ("esp", "ESP"),
                    ("traction_control", "Kontrola trakcji"),
                    ("lane_assist", "Asystent pasa ruchu"),
                    ("blind_spot", "Czujnik martwego pola"),
                    ("adaptive_cruise", "Adaptacyjny tempomat"),
                    ("emergency_brake", "Automatyczne hamowanie awaryjne"),
                    ("airbags", "Poduszki powietrzne"),
                    ("parking_sensors_front", "Czujniki parkowania przód"),
                    ("parking_sensors_rear", "Czujniki parkowania tył"),
                    ("parking_camera", "Kamera cofania"),
                    ("360_camera", "Kamera 360°"),
                    ("auto_parking", "Asystent parkowania"),
                    ("automatic", "Automatyczna skrzynia biegów"),
                    ("manual", "Manualna skrzynia biegów"),
                    ("awd", "Napęd 4x4"),
                    ("hybrid", "Napęd hybrydowy"),
                    ("electric", "Samochód elektryczny"),
                    ("cruise_control", "Tempomat"),
                    ("panoramic_roof", "Panoramiczny dach"),
                    ("sunroof", "Szyberdach"),
                    ("roof_rack", "Bagażnik dachowy"),
                    ("tow_hook", "Hak holowniczy"),
                    ("winter_tires", "Opony zimowe"),
                    ("child_seat", "Fotelik dziecięcy"),
                    ("isofix", "ISOFIX"),
                ],
                max_length=480,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="state",
            field=models.CharField(
                choices=[
                    ("wroclaw", "Wrocław"),
                    ("lublin", "Lublin"),
                    ("krakow", "Kraków"),
                    ("warszawa", "Warszawa"),
                    ("rzeszow", "Rzeszów"),
                    ("bialystok", "Białystok"),
                    ("gdansk", "Gdańsk"),
                    ("kielce", "Kielce"),
                    ("poznan", "Poznań"),
                    ("szczecin", "Szczecin"),
                ],
                max_length=100,
            ),
        ),
    ]
