# Generated by Django 6.0 on 2025-12-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0002_remove_car_created_date_remove_car_is_featured_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="doors",
            field=models.IntegerField(
                choices=[
                    (2, "2 Dźwiowy"),
                    (3, "3 Dźwiowy"),
                    (4, "4 Dźwiowy"),
                    (5, "5 Dźwiowy"),
                ]
            ),
        ),
    ]
