# Generated by Django 6.0 on 2025-12-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0003_alter_car_doors"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
