# Generated by Django 6.0 on 2025-12-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0004_car_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
