# Generated by Django 6.0 on 2025-12-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0006_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="actual_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="final_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
